# This file contains parameters for the SLAM Toolbox, based on Prac 3 requirements.
# It defines the map resolution, frame IDs, and other critical mapping settings.
slam_toolbox:
  ros__parameters:
    # Required parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_sim_time: True

    # Map resolution, as specified in the project brief
    resolution: 0.05

    # Other common parameters for tuning
    map_update_interval: 1.0 # Update the map less frequently to save CPU
    transform_publish_period: 0.2 # How often to publish the map->odom transform
    mode: "mapping" # Can be "mapping" or "localization"
